### ISSUE TITLE
上传图片失败

### ISSUE THREAD

**Issue by SoybeanCheung** [akira-cn/matrix#8]
当我准备上传图片的时候，报如下的错误：

>  [Error] TypeError: require(...).bind is not a function
    at Object.getInstance (F:\programmer\workspace\yueqiu\app\common\service\uploader.js:16:67)

**Comment by akira-cn** [comment]
你好，可能是浏览器兼容性问题？请使用chrome浏览器或IE9以上的版本。

**Comment by nasawz** [comment]
我也遇到同样问题。 chrome浏览器

还有后台的翻页功能好像也不好用

**Comment by akira-cn** [comment]
的确有问题，是Babel升级之后的export default机制变了，回头我更新下

**Comment by snadn** [comment]
@akira-cn 提了个pr #9 修复了该问题

**Comment by snadn** [comment]
翻页有问题+1

**Comment by akira-cn** [comment]
翻页修复了
